### ISSUE TITLE
🚲 Rename SemVer to something else?

### ISSUE THREAD

**Issue by eed3si9n** [coursier/versions#7]
`VersionCompatibility.SemVer` while useful denotes something different from the Semantic Versioning Specification, as it is acknowledged by the existence of `SemVerSpec`.

I feel uncomfortable encoding this into `build.sbt` or POM as "semver". Could we rename this to something like "semver-zero"?

**Comment by eed3si9n** [comment]
@julienrf suggested "Scala Semver" but it might be confused with the `epoch.major.minor` version scheme adopted by Scala standard library and compiler.

**Comment by eed3si9n** [comment]
Related to this (I think), [Binary Compatibility for Library Authors](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html) adds additional rules:

1. MAJOR version if backward binary compatibility is broken,
2. MINOR version if backward source compatibility is broken, and
3. PATCH version to signal neither binary nor source incompatibility.

that are not part of the original Semantic Versioning, but something useful to Scala (binary) ecosystem. It might be good to capture that in Scaladoc etc as well if we're going to enforce that elsewhere.

**Comment by alexarchambault** [comment]
What about `EarlySemVer` / `early-semver` as a name?

**Comment by eed3si9n** [comment]
`early-semver` is easy to remember, so that's good.

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/coursier/versions/pull/8
